
package soapgen.java.host;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PutServiceImplService")
public class PutServiceImplService
    extends Service
{

    private final static URL PUTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(PutServiceImplService.class.getName());
    private URL wsdlLocation;
    private QName serviceName;

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = PutServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://10.0.1.2:9080/PutService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.0.1.2:9080/PutService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PUTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public PutServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
        this.wsdlLocation = wsdlLocation;
        this.serviceName = serviceName;
    }

    public PutServiceImplService() {
        super(PUTSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://10.0.1.2:9080/PutService?wsdl", "PutServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns PutService
     */
    @WebEndpoint(name = "PutServiceImplPort")
    public PutService getPutServiceImplPort() {
        return super.getPort(new QName(serviceName.getNamespaceURI(), "PutServiceImplPort"), PutService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PutService
     */
    @WebEndpoint(name = "PutServiceImplPort")
    public PutService getPutServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName(serviceName.getNamespaceURI(), "PutServiceImplPort"), PutService.class, features);
    }

}
