
package soapgen.python;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PutDispatcherPortType", targetNamespace = "http://localhost:8008/put.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PutDispatcherPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns localhost._8008.put.PutResponse
     */
    @WebMethod(operationName = "Put", action = "http://localhost:8008Put")
    @WebResult(name = "PutResponse", targetNamespace = "http://localhost:8008/put.wsdl", partName = "parameters")
    public PutResponse put(
            @WebParam(name = "Put", targetNamespace = "http://localhost:8008/put.wsdl", partName = "parameters")
            Put parameters);

}
