
package server.completion;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CompletionServiceImplService", targetNamespace = "http://completion.server/")
public class CompletionServiceImplService
    extends Service
{

    private final static URL COMPLETIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPLETIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName COMPLETIONSERVICEIMPLSERVICE_QNAME = new QName("http://completion.server/", "CompletionServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/CompletionService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPLETIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        COMPLETIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CompletionServiceImplService() {
        super(__getWsdlLocation(), COMPLETIONSERVICEIMPLSERVICE_QNAME);
    }

    public CompletionServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPLETIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public CompletionServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, COMPLETIONSERVICEIMPLSERVICE_QNAME);
    }

    public CompletionServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPLETIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public CompletionServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompletionServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CompletionService
     */
    @WebEndpoint(name = "CompletionServiceImplPort")
    public CompletionService getCompletionServiceImplPort() {
        return super.getPort(new QName("http://completion.server/", "CompletionServiceImplPort"), CompletionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompletionService
     */
    @WebEndpoint(name = "CompletionServiceImplPort")
    public CompletionService getCompletionServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://completion.server/", "CompletionServiceImplPort"), CompletionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPLETIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw COMPLETIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return COMPLETIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
